-- BIZU FLASHCARDS — PC/AP 2026 — OFICIAL INVESTIGADOR
-- Execute em um projeto Supabase dedicado.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.access_grants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_code text not null default 'pcap_oficial_investigador_2026',
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, product_code)
);

create table if not exists public.subjects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  order_index integer not null default 0,
  question_count integer not null default 0 check (question_count >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.topics (
  id uuid primary key default gen_random_uuid(),
  subject_id uuid not null references public.subjects(id) on delete cascade,
  slug text not null unique,
  name text not null,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  topic_id uuid not null references public.topics(id) on delete cascade,
  front text not null,
  back text not null,
  reference text,
  difficulty smallint not null default 2 check (difficulty between 1 and 3),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  rating text not null check (rating in ('again','hard','know')),
  last_reviewed_at timestamptz not null default now(),
  next_review_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, flashcard_id)
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, flashcard_id)
);

create index if not exists idx_topics_subject on public.topics(subject_id, order_index);
create index if not exists idx_flashcards_topic on public.flashcards(topic_id) where active = true;
create index if not exists idx_reviews_due on public.reviews(user_id, next_review_at);
create index if not exists idx_access_user on public.access_grants(user_id, active);

alter table public.profiles enable row level security;
alter table public.access_grants enable row level security;
alter table public.subjects enable row level security;
alter table public.topics enable row level security;
alter table public.flashcards enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;

-- Permissões da Data API. RLS continua sendo a camada de autorização.
revoke all on public.profiles, public.access_grants, public.subjects, public.topics, public.flashcards, public.reviews, public.favorites from anon;
grant select, insert, update on public.profiles to authenticated;
grant select on public.access_grants to authenticated;
grant select on public.subjects, public.topics, public.flashcards to authenticated;
grant select, insert, update, delete on public.reviews, public.favorites to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- O aluno enxerga e edita apenas seu próprio perfil.
create policy "profile_select_own" on public.profiles for select to authenticated
using ((select auth.uid()) = id);
create policy "profile_insert_own" on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);
create policy "profile_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- O aluno só enxerga sua própria liberação.
create policy "access_select_own" on public.access_grants for select to authenticated
using ((select auth.uid()) = user_id);

-- Conteúdo disponível apenas para quem possui acesso ativo ao produto.
create policy "subjects_paid_access" on public.subjects for select to authenticated using (
  exists (select 1 from public.access_grants ag where ag.user_id = (select auth.uid()) and ag.product_code = 'pcap_oficial_investigador_2026' and ag.active and (ag.expires_at is null or ag.expires_at > now()))
  or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
);
create policy "topics_paid_access" on public.topics for select to authenticated using (
  exists (select 1 from public.access_grants ag where ag.user_id = (select auth.uid()) and ag.product_code = 'pcap_oficial_investigador_2026' and ag.active and (ag.expires_at is null or ag.expires_at > now()))
  or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
);
create policy "flashcards_paid_access" on public.flashcards for select to authenticated using (
  active and exists (select 1 from public.access_grants ag where ag.user_id = (select auth.uid()) and ag.product_code = 'pcap_oficial_investigador_2026' and ag.active and (ag.expires_at is null or ag.expires_at > now()))
  or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin'
);

-- Histórico e favoritos são privados por aluno.
create policy "reviews_select_own" on public.reviews for select to authenticated using ((select auth.uid()) = user_id);
create policy "reviews_insert_own" on public.reviews for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "reviews_update_own" on public.reviews for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "reviews_delete_own" on public.reviews for delete to authenticated using ((select auth.uid()) = user_id);
create policy "favorites_select_own" on public.favorites for select to authenticated using ((select auth.uid()) = user_id);
create policy "favorites_insert_own" on public.favorites for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "favorites_delete_own" on public.favorites for delete to authenticated using ((select auth.uid()) = user_id);

-- Administradores: conteúdo e liberações. O papel deve ficar em app_metadata, nunca em user_metadata.
grant insert, update, delete on public.access_grants, public.subjects, public.topics, public.flashcards to authenticated;
create policy "admin_access_manage" on public.access_grants for all to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');
create policy "admin_subjects_manage" on public.subjects for all to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');
create policy "admin_topics_manage" on public.topics for all to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');
create policy "admin_flashcards_manage" on public.flashcards for all to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin')
with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

insert into public.subjects (slug, name, order_index, question_count) values
('portugues','Língua Portuguesa',1,8),
('rlm','Raciocínio Lógico-Matemático',2,8),
('estatistica','Noções de Estatística e Análise de Dados',3,8),
('contabilidade','Noções de Contabilidade e Análise Financeira',4,8),
('informatica','Noções de Informática',5,12),
('penal','Direito Penal e Legislação Penal Especial',6,8),
('processo-penal','Direito Processual Penal e Legislação Processual Penal Especial',7,8),
('constitucional','Direito Constitucional',8,5),
('administrativo','Direito Administrativo',9,5),
('direitos-humanos','Direitos Humanos',10,4),
('historia-ap','História do Amapá',11,2),
('geografia-ap','Geografia do Amapá',12,2),
('legislacao','Legislação Institucional',13,2)
on conflict (slug) do update set name=excluded.name, order_index=excluded.order_index, question_count=excluded.question_count;
