begin;

alter table public.profiles
  add column if not exists email text,
  add column if not exists daily_goal integer not null default 50 check (daily_goal between 1 and 500);

update public.profiles p
set email = u.email
from auth.users u
where u.id = p.id and (p.email is null or p.email <> u.email);

create table if not exists public.review_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  flashcard_id uuid not null references public.flashcards(id) on delete cascade,
  rating text not null check (rating in ('again','hard','know')),
  reviewed_at timestamptz not null default now()
);
create index if not exists idx_review_events_user_date on public.review_events(user_id, reviewed_at desc);
create index if not exists idx_review_events_flashcard on public.review_events(flashcard_id);
alter table public.review_events enable row level security;
grant select, insert on public.review_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "review_events_select_own" on public.review_events;
drop policy if exists "review_events_insert_own" on public.review_events;
create policy "review_events_select_own" on public.review_events for select to authenticated using ((select auth.uid()) = user_id);
create policy "review_events_insert_own" on public.review_events for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "profile_select_own" on public.profiles;
drop policy if exists "admin_profiles_select" on public.profiles;
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles for select to authenticated
using ((select auth.uid()) = id or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "access_select_own" on public.access_grants;
drop policy if exists "admin_access_select" on public.access_grants;
drop policy if exists "access_select_own_or_admin" on public.access_grants;
create policy "access_select_own_or_admin" on public.access_grants for select to authenticated
using ((select auth.uid()) = user_id or ((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

create or replace function public.sync_profile_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email,''), '@', 1)))
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(public.profiles.full_name, excluded.full_name);
  return new;
end;
$$;
revoke all on function public.sync_profile_email() from public;
revoke all on function public.sync_profile_email() from anon;
revoke all on function public.sync_profile_email() from authenticated;

drop trigger if exists trg_sync_profile_email on auth.users;
create trigger trg_sync_profile_email
after insert or update of email on auth.users
for each row execute function public.sync_profile_email();

commit;
